### CE 103- INTRODUCTION TO COMPUTERS and PROGRAMMING

### _The topics of the week !_

- Numerical Routines **_NumPy_**
    - Array
    - Multidimensional Arrays
    - Matrix manipulations

#### List VS Array

We learned about both lists and arrays last week, but, what is the difference between them? When to use a Python array or a list? 

Python has lots of data structures with different functions and features. Lists, tuples, dictionaries are some of the built-in data structures that you don't have to import. But array is an additional data structure that has to be imported as a module or an extra package. To use an array, it has to be imported from the **_NumPy package_**.

![](./Figures/array_vs_list.png)

So, if you have a relatively short sequence of items and you don't plan to use any mathematical operation, its better to use list, on the other hans, if you have a very long data sequence (in same datatype) **_NumPy package_** will be very useful and highly recommended even if you plan to use mathemetical operations. 

## Array in Python 

Array is a python module which defines the data structure holds a fix number of items with same datatypes. An array stores items which called "elements" and each location of an element described by "index". "Element" and "index" are important terms to understand the concept of array. 

To use arrays in Python, we need to import **_NumPy package_**. Because array is not a fundamental data type like strings, integer etc., we need to import the  **_NumPy package_** and declare an array. An array referred as _"ndarray"_ is shorthand for N-dimensional array which is with any number of dimension.


---
# NumPy

NumPy (Numerical Python) is an open source Python library which is very useful general-purpose array-processing package and a core of the scientific and engineering computing ecosystem of Python. It includes multidimensional array object, broadcasting functions, linear algebra calculations, Fourier transform and more. The NumPy library also contains matrix data structures and can be used to perform mathematical operations on arrays. NumPy can allow a wide variety of datatypes speedly. 

If you have Python you can install NumPy as below;

<font color=blue>conda install numpy<font>

,or,

<font color=blue>pip install numpy<font>

#### **How to import NumPy ?**

We prefer NumPy because it provides an enormous range of fast and efficient mathematical operations. 
Not only for NumPy but also for all packages or libraries in Python, you need to use statement **_"import"_** to make them accessible.  

In [539]:
import numpy as np

: np stands for an abbreviation in order to keep code standardized and make it easier to understand and faster to run. 

In [540]:
# the command below will bring you to the reference documentation;

help(np.array)

---

### **NumPy Array**

The NumPy array can be defined as a grid of elements which can be indexed in various ways. An array in Numpy is a table of element with same type which indexed by tuple of positive integers. Tuple of integers giving the size of the array is the _shape_ of an array. Dimensions of a NumPy array is called _axes_. The number of axes in array called _rank_. A _vector_ is an array with a single column, a _matrix_ is an array with multiple columns.

In [482]:
import numpy as np

a = np.array([1,2,3])  # this is a rank = 1 array

print(type(a))   # print type of the array
print(a[1])      # indexing elements of array
print(a.dtype)   # print type of elements in array
print(a.shape)   # print shape of array
print(a.ndim)    # print number of dimensions (axes)
print(a.size)    # print size of the array

<class 'numpy.ndarray'>
2
int64
(3,)
1
3


In [483]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[1,2])

(2, 3)
6


---
#### **_Specify a numpy array with fuctions;_**

In [484]:
import numpy as np

a= np.zeros((3,4))     # create a matrix of zeros
print(a,'\n')

b = np.ones((2,3))     # create a matrix of ones
print(b,'\n')

c = np.random.random((1,3))  # create a matrix of random numbers
print(c,'\n')

d = np.full((3,2),5)  # create a constant matrix
print(d,'\n')

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[0.84030669 0.99304365 0.99819033]] 

[[5 5]
 [5 5]
 [5 5]] 



In [485]:
e = np.eye(3)        # create an identity matrix
print(e,'\n')

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [486]:
f = np.array([[1, 3, 5], [7, 9, 11]], dtype = 'float')  # create array from a float type list 
print(f,'\n')

[[ 1.  3.  5.]
 [ 7.  9. 11.]] 



In [487]:
gg = np.arange(9)
print(gg)
g = np.arange(1, 12, 2)  # create an array of integers between 1 to 12 with steps 2 (first #, last #, step size)
print(g,'\n')

[0 1 2 3 4 5 6 7 8]
[ 1  3  5  7  9 11] 



In [488]:
h = np.linspace(5, 15, 5) # create an array with 5 items between 5 to 15 
print(h,'\n') 

[ 5.   7.5 10.  12.5 15. ] 



In [489]:
i = np.random.random((4,4))
print(i,'\n')

j = i.reshape(2,2,2,2)
print(j,'\n')  

[[0.94608722 0.33056072 0.50815197 0.42840906]
 [0.69638841 0.35487764 0.82663057 0.70424716]
 [0.88761895 0.08600517 0.75076953 0.06813477]
 [0.11230799 0.32154756 0.70482116 0.16154017]] 

[[[[0.94608722 0.33056072]
   [0.50815197 0.42840906]]

  [[0.69638841 0.35487764]
   [0.82663057 0.70424716]]]


 [[[0.88761895 0.08600517]
   [0.75076953 0.06813477]]

  [[0.11230799 0.32154756]
   [0.70482116 0.16154017]]]] 



---
#### **_more array functions;_**


In [490]:
a = np.array([4, 2, 1, 5, 3])
print(np.append(a, [8,8]))         # Appends values to end of array
print(np.insert(a, 2, 55))         # Inserts values into array before index 2 (array,2,values)
print(np.delete(a, 3, axis = 0))   # delete row on index 3 of array
print(np.sort(a))

[4 2 1 5 3 8 8]
[ 4  2 55  1  5  3]
[4 2 1 3]
[1 2 3 4 5]


In [491]:
# comparison of two different array

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 1, 2])

print(a == b)
print(a > b)

# ,or, array-wise comparison can be used as below;
print(np.array_equal(a, b))


[False False False False]
[False False  True  True]
False


---
#### **_shape and resize array;_**


In [492]:
i = np.random.random([4,4])
print(i)

i.ndim           # gives number of dimensions of the array 
print(i.ndim)

print(np.size(i))  # gives total number of elements of the array
np.shape(i)        # gives the shape of the array



[[0.35070109 0.10206894 0.44660153 0.80520969]
 [0.61254075 0.0641514  0.4271081  0.72191871]
 [0.5768439  0.17575743 0.33684102 0.78753307]
 [0.85104751 0.66889787 0.67785567 0.23522294]]
2
16


(4, 4)

In [493]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# b = a.reshape(3,2) # gives a new shape to an array with same items, both arrays should have same number of elements.
b = a.reshape(4, 2)
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


---
#### **_Array indexing;_**

Arrays can be multidimensional, we should specify a slice for each dimension, just like in list operations.

In [494]:
a = np.array([[1,3,5],[2,4,6],[7,8,9]])
print(a,'\n')

b = a[:2,0:2]  # pull out the subarray of first 2 raws and columns 0 to 1
print(b,'\n')


[[1 3 5]
 [2 4 6]
 [7 8 9]] 

[[1 3]
 [2 4]] 



In [495]:
print(a[1,2])  # element value at 1th row, 2nd column 

6


In [496]:
b[0,1] = 11
print(b)

[[ 1 11]
 [ 2  4]]


In [497]:
a = np.array([[1,3,5],[2,4,6],[7,8,9]])

row1 = a[0, :]   
row2 = a[1:2, :]
print(row1, row2)

col1 = a[:,1]
col2 = a[:, 1:2]
print(col1, col2)

[1 3 5] [[2 4 6]]
[3 4 8] [[3]
 [4]
 [8]]


In [498]:
a = np.array([[1,3,5],[2,4,6],[7,8,9]])

print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

print(a[[0, 0], [1, 1]]) 
print(np.array([a[0, 1], a[0, 1]])) 

[1 4 7]
[1 4 7]
[3 3]
[3 3]


In [499]:
a = np.array([[1,3,5],[2,4,6],[7,8,9]])

b = np.array([0, 2, 0, 1]) 
print(a[np.arange(3)]) 

a[np.arange(3)] += 10
print( a )


[[1 3 5]
 [2 4 6]
 [7 8 9]]
[[11 13 15]
 [12 14 16]
 [17 18 19]]


In [500]:
a[0:2]

array([[11, 13, 15],
       [12, 14, 16]])

In [501]:
a = np.array([[3,4], [7, 1], [2, 4]])
bool_idx = (a > 2)
print(bool_idx) 

#print(a[bool_idx])   # print the values "true" for the condition a > 2
#print(a[a > 2])

[[ True  True]
 [ True False]
 [False  True]]


---
#### **_Datatypes_**

"dtype' command can be used to identify the type of an array

In [502]:
a = np.array([1,2])
print(a.dtype)         # Returns type of elements in array

int64


In [503]:
a = np.array([1.0, 2.0]) 
print(a.dtype)           

float64


In [504]:
a = np.array([1, 2], dtype=np.int64) 
print(a.dtype)                    

int64


In [505]:
a = np.array([1,2])
a.tolist()           # Convert array to a Python list

[1, 2]

In [506]:
np.info(np.ones)    # View documentation for "ones" properties

 ones(shape, dtype=None, order='C')

Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and order.

See Also
--------
zeros, ones_like

Examples
--------
>>> np.ones(5)
array([ 1.,  1.,  1.,  1.,  1.])

>>> np.ones((5,), dtype=int)
array([1, 1, 1, 1, 1])

>>> np.ones((2, 1))
array([[ 1.],
       [ 1.]])

>>> s = (2,2)
>>> np.ones(s)
array([[ 1.,  1.],
       [ 1.,  1.]])


---
#### **_Basic array operations_**

_Addition, subtraction, multiplication, division, etc._

In [507]:
# Lets define two different arrays; 

data = np.random.random([1,2])
ones = np.ones(2)

print(data, ones)

data + ones
data - ones
data * ones
data / data

#Operation between a vector and a scalar is allowed.

data * 2.5

[[0.2716638  0.37122724]] [1. 1.]


array([[0.6791595, 0.9280681]])

 _Maxinum, minimum, sum, mean, product, standard deviation, etc._

In [508]:
a = np.random.random([3,])
print(a)

[0.40492836 0.9573896  0.43001095]


In [509]:
b = np.random.rand(2,3)      # 2x3 array of random floats between 0–1
print(b)

[[0.3782329  0.46582747 0.24685883]
 [0.79606347 0.88884586 0.9596028 ]]


In [510]:
c = np.random.rand(3,1)*100  # 3x1 array of random floats between 0–100
print(c)

[[57.00457651]
 [61.25205296]
 [56.240308  ]]


In [511]:
d = np.random.randint(14,size=(3,5))    # 3x5 array with random ints between 0–4
print(d)

[[12  1  6 10  7]
 [ 6 10  2 13  7]
 [ 3 11  4  6 11]]


In [512]:
print(a.max())     # find the maximum value element in array
print(a.min())     # fint the minimum value element in array
print(a.sum())     # find the sum of the elements in array

0.9573895980333219
0.40492836357266027
1.7923289095961619


In [513]:
# we can use arithmetic operators to do element-wise operation on array;

a = np.array([1, 2, 5, 3]) 
  
print ( a+3)     # add a scalar to each element of array 
print (a-3)      # subtract a scalar from each element of array 
print (a*2)      # multiply each element by 2 
print (a**2)     # calculate square of each element  

# we can also multiply array by a scalar as below;
a *= 2
print (a) # modify existing array 
  

[4 5 8 6]
[-2 -1  2  0]
[ 2  4 10  6]
[ 1  4 25  9]
[ 2  4 10  6]


In [514]:
# we can use arithmetic operators to do operation on array;
  
a = np.array([[1, 3], [5, 7]]) 
b = np.array([[2, 4], [6, 8]]) 
   
print (a + b)       # add arrays with eachother
print (a + b)       # multiply arrays (elementwise multiplication)
print (a.dot(b))    # matrix multiplication 

[[ 3  7]
 [11 15]]
[[ 3  7]
 [11 15]]
[[20 28]
 [52 76]]


In [515]:
#we can also sort a NumPy array by np.sort;

a = np.array([[1, 4, 2], 
                 [3, 4, 6], 
              [0, -1, 5]])

print(np.sort(a, axis = None))  # Array elements in sorted orde
    
print(np.sort(a, axis = 1))    # sort array row-wise

[-1  0  1  2  3  4  4  5  6]
[[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [516]:
# NumPy also provides mathematical functions such as sin, cos, exp, transpose etc.

a = np.array([np.pi/2, np.pi*2, 3.14]) # create an array of sine values 
print (np.cos(a)) 
  
b = np.array([1, 2, 3]) # exponential values 
print (np.exp(b)) 
  
print(np.sqrt(b)) # square root of array values
print(np.log(b))  # logarithmic values of array elements

b = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]]) 
print ("\nOriginal array:\n", b) 
print ("Transpose of array:\n", b.T) # transpose of array 

[ 6.12323400e-17  1.00000000e+00 -9.99998732e-01]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [517]:
# we can find unique element in an array

a = np.array([1, 1, 2, 3, 4, 5, 6, 7, 2, 3, 1, 4, 8, 9, 0])
print(np.unique(a))


[0 1 2 3 4 5 6 7 8 9]


---
#### **_Matrix operations;_**

In [518]:
# Lets define an array which we can manipulate matrices also;

a = np.array([[1,2],[3,4]])
print(a)

print(a[0,1])
print(a[1::])
print(a[:,0])

[[1 2]
 [3 4]]
2
[[3 4]]
[1 3]


In [519]:
print(a.max())     # find the maximum value element in matrix
print(a.min())     # fint the minimum value element in matrix
print(a.sum())     # find the sum of the elements in matrix

4
1
10


![](./Figures/array-sum.png)

In [520]:
print(a.sum(axis=0))  # column sums
print(a.sum(axis=1))  # row sums

[4 6]
[3 7]


In [521]:
# find maximum and minimum rows or columns of the matrix
print(a.max(axis=0))
print(a.max(axis=1))

[3 4]
[2 4]


In [522]:
# Two matrices at same size can be multiply or add with each other

data = np.random.random([2,3])
ones = np.ones([2,3])

print(data)
print(ones)

a = data + ones
print(a)

# Arithmetic operations on matrices with different size con do if only one matrix thas only one column or row

b = data + np.ones([1,3])


[[0.14285635 0.00261717 0.31180399]
 [0.42464343 0.5585037  0.69318662]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.14285635 1.00261717 1.31180399]
 [1.42464343 1.5585037  1.69318662]]


For matrix multiplications use the **_dot_** function to compute inner product of vector instead of **' * '** that unlike MATLAB. **_dot_** product can also be used for a vector by a matrix or matrix by matrix multiplications.

In [523]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([2,4])
w = np.array([1,2])

print(v.dot(w))         # Inner product of vectors
print(np.dot(v, w))

print(x.dot(v))         # Matrix / vector product
print(np.dot(x, v))

print(x.dot(y))         # Matrix / matrix product
print(np.dot(x, y))

10
10
[10 22]
[10 22]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [524]:
# to transpose a matrix, use the T attribute of an array object:

a = np.array([[1,2], [3,4]])

In [525]:
print(a, '\n') 

[[1 2]
 [3 4]] 



In [526]:
print(a.T,'\n')   

[[1 3]
 [2 4]] 



In [527]:
a = np.arange(25).reshape(5,5)

print(a.diagonal())
print(a.diagonal(1))
print(a.diagonal(-1))
print(a.diagonal(-2))

[ 0  6 12 18 24]
[ 1  7 13 19]
[ 5 11 17 23]
[10 16 22]


In [528]:
a = np.arange(15).reshape(3,5)

print(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [529]:
a = np.array([[1,2], [3,4]])

print(np.reshape(a,[4,1]))  # shape refers to the array size or dimension size
np.transpose(a)

[[1]
 [2]
 [3]
 [4]]


array([[1, 3],
       [2, 4]])

---
#### **_N-deminsional arrays_**

![](./Figures/3d-array.png)

Not only 3D, it may be in 4 or more dimensional array. N-dimensional arrays are widely used in Machine Learning algorithms. Here is an example of 3D NumPy array defined below;

In [530]:
a = np.random.random((4,3,2))  # refers 3D array with 3 values as 4,3,2.

print(a)

[[[0.39570033 0.45442201]
  [0.48645826 0.43808904]
  [0.42316404 0.83818979]]

 [[0.32425814 0.06970726]
  [0.7385326  0.68882506]
  [0.18288533 0.91079792]]

 [[0.10811512 0.55515685]
  [0.11926944 0.77703459]
  [0.27290666 0.9276458 ]]

 [[0.83496198 0.44538112]
  [0.78472587 0.19536607]
  [0.46140665 0.77831207]]]


In [531]:
a.std()   # calculates the standart deviation of elemnts in array

0.2656804792204241

In [532]:
a.var()   # calculates variance of the array

0.07058611703879421

In [533]:
a.mean()   # calculates the average value of array

0.5088046658254868

In [534]:
a.cumsum()  # calculates the cumulative summation of elements in the array

array([ 0.39570033,  0.85012234,  1.3365806 ,  1.77466963,  2.19783367,
        3.03602346,  3.3602816 ,  3.42998886,  4.16852146,  4.85734652,
        5.04023185,  5.95102977,  6.05914489,  6.61430174,  6.73357118,
        7.51060577,  7.78351243,  8.71115823,  9.54612021,  9.99150133,
       10.7762272 , 10.97159326, 11.43299991, 12.21131198])

In [535]:
a = np.array([[2,3,4],[1,4,3],[2,5,6]])
print(a)

[[2 3 4]
 [1 4 3]
 [2 5 6]]


In [536]:
a.conj()    # gives the conjugate of elements of the array

array([[2, 3, 4],
       [1, 4, 3],
       [2, 5, 6]])

In [537]:
a.trace(-2)  # perform a summation of each diagonal.

2

In [538]:
a = np.array([3.2, 2, 1])
np.roots(a)

array([-0.3125+0.46351241j, -0.3125-0.46351241j])

---

## Homework #3
---
Please solve the deterministic linear equation ( A x = B ) given below by using NumPy. You can represent the problem as matrices and apply matrix algebra to solve it.

_2p + 3q + r = 9_

_p + 5q + 2r = 11_

_p = 6_

Formulize the problem with matrices and solve it for the vector x.

PS: Do not forget to upload your pdf files to http://derskutusu.gtu.edu.tr/

---